#!/bin/bash

source "$CONFIG_DIR/colors.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### Changing Defaults #####

default=(
    padding_left=5
    padding_right=5
    icon.font="Hack Nerd Font:Bold:17.0"
    label.font="SF Pro:Semibold:17.0"
    icon.color=0xffffffff
    label.color=0xffffffff
    icon.padding_left=4
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=4
    updates=on
)
sketchybar --default "${default[@]}"

##### Adding aeropsace layouts #####
# Add the aerospace_workspace_change event correponded in aerospace.toml
sketchybar --add event aerospace_workspace_change

##### Adding Left Items #####
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

##### Adding Middle Items #####
source $ITEM_DIR/media.sh

##### Adding Right Items #####
source $ITEM_DIR/clock.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
